import { Locale } from './types';

type Translation = {
  title: string;
  search: string;
  empty: string;
  addNote: string;
  addTodo: string;
  textMode: string;
  todoMode: string;
  calculator: string;
  clock: string;
  drawing: string;
  spreadsheet: string;
  calendar: string;
  settings: string;
  theme: string;
  lightTheme: string;
  darkTheme: string;
  background: string;
  backgroundPosition: string;
  chooseImage: string;
  clearImage: string;
  opacity: string;
  language: string;
  noteTitle: string;
  noteContent: string;
  taskPlaceholder: string;
  save: string;
  secretCode: string;
};

export const translations: Record<Locale, Translation> = {
  ar: { title: 'التطبيق', search: 'بحث...', empty: 'لا توجد ملاحظات. اضغط على + للإضافة.', addNote: 'ملاحظة نصية', addTodo: 'قائمة مهام', textMode: 'نص', todoMode: 'مهام', calculator: 'الآلة الحاسبة', clock: 'الساعة', drawing: 'لوحة رسم', spreadsheet: 'جدول بيانات', calendar: 'التقويم', settings: 'الإعدادات', theme: 'المظهر', lightTheme: 'فاتح', darkTheme: 'داكن', background: 'خلفية التطبيق', backgroundPosition: 'موضع الخلفية', chooseImage: 'اختيار صورة', clearImage: 'إزالة الصورة', opacity: 'شفافية الواجهة', language: 'اللغة', noteTitle: 'العنوان', noteContent: 'المحتوى...', taskPlaceholder: 'إضافة مهمة', save: 'حفظ', secretCode: 'الرمز السري' },
  en: { title: 'App', search: 'Search...', empty: 'No notes yet. Tap + to add.', addNote: 'Text Note', addTodo: 'To-Do List', textMode: 'Text', todoMode: 'To-Do', calculator: 'Calculator', clock: 'Clock', drawing: 'Drawing', spreadsheet: 'Spreadsheet', calendar: 'Calendar', settings: 'Settings', theme: 'Theme', lightTheme: 'Light', darkTheme: 'Dark', background: 'Background', backgroundPosition: 'Position', chooseImage: 'Choose Image', clearImage: 'Clear Image', opacity: 'UI Opacity', language: 'Language', noteTitle: 'Title', noteContent: 'Content...', taskPlaceholder: 'Add Task', save: 'Save', secretCode: 'Secret Code' },
  es: { title: 'App', search: 'Buscar...', empty: 'No hay notas.', addNote: 'Nota de texto', addTodo: 'Lista de tareas', textMode: 'Texto', todoMode: 'Tareas', calculator: 'Calculadora', clock: 'Reloj', drawing: 'Dibujo', spreadsheet: 'Hoja de cálculo', calendar: 'Calendario', settings: 'Ajustes', theme: 'Tema', lightTheme: 'Claro', darkTheme: 'Oscuro', background: 'Fondo', backgroundPosition: 'Posición', chooseImage: 'Elegir imagen', clearImage: 'Borrar', opacity: 'Opacidad', language: 'Idioma', noteTitle: 'Título', noteContent: 'Contenido...', taskPlaceholder: 'Añadir tarea', save: 'Guardar', secretCode: 'Código secreto' },
  fr: { title: 'App', search: 'Rechercher...', empty: 'Aucune note.', addNote: 'Note', addTodo: 'Liste de tâches', textMode: 'Texte', todoMode: 'Tâches', calculator: 'Calculatrice', clock: 'Horloge', drawing: 'Dessin', spreadsheet: 'Tableur', calendar: 'Calendrier', settings: 'Paramètres', theme: 'Thème', lightTheme: 'Clair', darkTheme: 'Sombre', background: 'Fond', backgroundPosition: 'Position', chooseImage: 'Choisir', clearImage: 'Effacer', opacity: 'Opacité', language: 'Langue', noteTitle: 'Titre', noteContent: 'Contenu...', taskPlaceholder: 'Ajouter', save: 'Enregistrer', secretCode: 'Code secret' },
  de: { title: 'App', search: 'Suchen...', empty: 'Keine Notizen.', addNote: 'Notiz', addTodo: 'Aufgabenliste', textMode: 'Text', todoMode: 'Aufgaben', calculator: 'Taschenrechner', clock: 'Uhr', drawing: 'Zeichnung', spreadsheet: 'Tabelle', calendar: 'Kalender', settings: 'Einstellungen', theme: 'Thema', lightTheme: 'Hell', darkTheme: 'Dunkel', background: 'Hintergrund', backgroundPosition: 'Position', chooseImage: 'Bild wählen', clearImage: 'Löschen', opacity: 'Deckkraft', language: 'Sprache', noteTitle: 'Titel', noteContent: 'Inhalt...', taskPlaceholder: 'Aufgabe', save: 'Speichern', secretCode: 'Geheimcode' },
  it: { title: 'App', search: 'Cerca...', empty: 'Nessuna nota.', addNote: 'Nota', addTodo: 'Lista', textMode: 'Testo', todoMode: 'Elenco', calculator: 'Calcolatrice', clock: 'Orologio', drawing: 'Disegno', spreadsheet: 'Foglio calcolo', calendar: 'Calendario', settings: 'Impostazioni', theme: 'Tema', lightTheme: 'Chiaro', darkTheme: 'Scuro', background: 'Sfondo', backgroundPosition: 'Posizione', chooseImage: 'Scegli', clearImage: 'Rimuovi', opacity: 'Opacità', language: 'Lingua', noteTitle: 'Titolo', noteContent: 'Contenuto...', taskPlaceholder: 'Aggiungi', save: 'Salva', secretCode: 'Codice segreto' },
  pt: { title: 'App', search: 'Buscar...', empty: 'Sem notas.', addNote: 'Nota', addTodo: 'Lista', textMode: 'Texto', todoMode: 'Lista', calculator: 'Calculadora', clock: 'Relógio', drawing: 'Desenho', spreadsheet: 'Planilha', calendar: 'Calendário', settings: 'Configurações', theme: 'Tema', lightTheme: 'Claro', darkTheme: 'Escuro', background: 'Fundo', backgroundPosition: 'Posição', chooseImage: 'Escolher', clearImage: 'Remover', opacity: 'Opacidade', language: 'Idioma', noteTitle: 'Título', noteContent: 'Conteúdo...', taskPlaceholder: 'Adicionar', save: 'Salvar', secretCode: 'Código secreto' },
  ru: { title: 'App', search: 'Поиск...', empty: 'Нет заметок.', addNote: 'Заметка', addTodo: 'Список задач', textMode: 'Текст', todoMode: 'Список', calculator: 'Калькулятор', clock: 'Часы', drawing: 'Рисование', spreadsheet: 'Таблица', calendar: 'Календарь', settings: 'Настройки', theme: 'Тема', lightTheme: 'Светлая', darkTheme: 'Темная', background: 'Фон', backgroundPosition: 'Позиция', chooseImage: 'Выбрать', clearImage: 'Удалить', opacity: 'Непрозрачность', language: 'Язык', noteTitle: 'Заголовок', noteContent: 'Текст...', taskPlaceholder: 'Добавить', save: 'Сохранить', secretCode: 'Секретный код' },
  zh: { title: 'App', search: '搜索...', empty: '没有笔记', addNote: '文本笔记', addTodo: '待办事项', textMode: '文本', todoMode: '待办', calculator: '计算器', clock: '时钟', drawing: '画板', spreadsheet: '电子表格', calendar: '日历', settings: '设置', theme: '主题', lightTheme: '亮色', darkTheme: '暗色', background: '背景', backgroundPosition: '位置', chooseImage: '选择图片', clearImage: '清除图片', opacity: '不透明度', language: '语言', noteTitle: '标题', noteContent: '内容...', taskPlaceholder: '添加任务', save: '保存', secretCode: '密码' },
  ja: { title: 'App', search: '検索...', empty: 'メモはありません', addNote: 'テキストメモ', addTodo: 'ToDoリスト', textMode: 'テキスト', todoMode: 'ToDo', calculator: '電卓', clock: '時計', drawing: 'お絵かき', spreadsheet: 'スプレッドシート', calendar: 'カレンダー', settings: '設定', theme: 'テーマ', lightTheme: 'ライト', darkTheme: 'ダーク', background: '背景', backgroundPosition: '位置', chooseImage: '画像を選択', clearImage: 'クリア', opacity: '不透明度', language: '言語', noteTitle: 'タイトル', noteContent: '内容...', taskPlaceholder: 'タスクを追加', save: '保存', secretCode: '暗号' },
  ko: { title: 'App', search: '검색...', empty: '메모 없음', addNote: '텍스트 메모', addTodo: '할 일 목록', textMode: '텍스트', todoMode: '할 일', calculator: '계산기', clock: '시계', drawing: '그리기', spreadsheet: '스프레드시트', calendar: '달력', settings: '설정', theme: '테마', lightTheme: '라이트', darkTheme: '다크', background: '배경', backgroundPosition: '위치', chooseImage: '이미지 선택', clearImage: '지우기', opacity: '투명도', language: '언어', noteTitle: '제목', noteContent: '내용...', taskPlaceholder: '작업 추가', save: '저장', secretCode: '비밀 코드' },
  hi: { title: 'App', search: 'खोज...', empty: 'कोई नोट नहीं', addNote: 'नोट', addTodo: 'कार्य सूची', textMode: 'पाठ', todoMode: 'कार्य', calculator: 'कैलकुलेटर', clock: 'घड़ी', drawing: 'ड्राइंग', spreadsheet: 'स्प्रेडशीट', calendar: 'कैलेंडर', settings: 'सेटिंग्स', theme: 'थीम', lightTheme: 'लाइट', darkTheme: 'डार्क', background: 'पृष्ठभूमि', backgroundPosition: 'स्थिति', chooseImage: 'छवि चुनें', clearImage: 'हटाएं', opacity: 'अस्पष्टता', language: 'भाषा', noteTitle: 'शीर्षक', noteContent: 'सामग्री...', taskPlaceholder: 'कार्य जोड़ें', save: 'सहेजें', secretCode: 'गुप्त कोड' },
  tr: { title: 'App', search: 'Ara...', empty: 'Not yok.', addNote: 'Not', addTodo: 'Yapılacaklar', textMode: 'Metin', todoMode: 'Görev', calculator: 'Hesap Makinesi', clock: 'Saat', drawing: 'Çizim', spreadsheet: 'E-Tablo', calendar: 'Takvim', settings: 'Ayarlar', theme: 'Tema', lightTheme: 'Açık', darkTheme: 'Koyu', background: 'Arka plan', backgroundPosition: 'Konum', chooseImage: 'Seç', clearImage: 'Sil', opacity: 'Opaklık', language: 'Dil', noteTitle: 'Başlık', noteContent: 'İçerik...', taskPlaceholder: 'Ekle', save: 'Kaydet', secretCode: 'Gizli Kod' },
  nl: { title: 'App', search: 'Zoeken...', empty: 'Geen notities.', addNote: 'Notitie', addTodo: 'Takenlijst', textMode: 'Tekst', todoMode: 'Taak', calculator: 'Rekenmachine', clock: 'Klok', drawing: 'Tekenen', spreadsheet: 'Spreadsheet', calendar: 'Kalender', settings: 'Instellingen', theme: 'Thema', lightTheme: 'Licht', darkTheme: 'Donker', background: 'Achtergrond', backgroundPosition: 'Positie', chooseImage: 'Kies', clearImage: 'Wissen', opacity: 'Dekking', language: 'Taal', noteTitle: 'Titel', noteContent: 'Inhoud...', taskPlaceholder: 'Toevoegen', save: 'Opslaan', secretCode: 'Geheime code' },
  pl: { title: 'App', search: 'Szukaj...', empty: 'Brak notatek.', addNote: 'Notatka', addTodo: 'Lista zadań', textMode: 'Tekst', todoMode: 'Zadania', calculator: 'Kalkulator', clock: 'Zegar', drawing: 'Rysowanie', spreadsheet: 'Arkusz', calendar: 'Kalendarz', settings: 'Ustawienia', theme: 'Motyw', lightTheme: 'Jasny', darkTheme: 'Ciemny', background: 'Tło', backgroundPosition: 'Pozycja', chooseImage: 'Wybierz', clearImage: 'Usuń', opacity: 'Krycie', language: 'Język', noteTitle: 'Tytuł', noteContent: 'Treść...', taskPlaceholder: 'Dodaj', save: 'Zapisz', secretCode: 'Tajny kod' },
  sv: { title: 'App', search: 'Sök...', empty: 'Inga anteckningar.', addNote: 'Anteckning', addTodo: 'Att göra', textMode: 'Text', todoMode: 'Uppgift', calculator: 'Kalkylator', clock: 'Klocka', drawing: 'Ritning', spreadsheet: 'Kalkylblad', calendar: 'Kalender', settings: 'Inställningar', theme: 'Tema', lightTheme: 'Ljus', darkTheme: 'Mörk', background: 'Bakgrund', backgroundPosition: 'Position', chooseImage: 'Välj', clearImage: 'Rensa', opacity: 'Opacitet', language: 'Språk', noteTitle: 'Titel', noteContent: 'Innehåll...', taskPlaceholder: 'Lägg till', save: 'Spara', secretCode: 'Hemlig kod' },
  vi: { title: 'App', search: 'Tìm...', empty: 'Trống.', addNote: 'Ghi chú', addTodo: 'Danh sách', textMode: 'Văn bản', todoMode: 'Nhiệm vụ', calculator: 'Máy tính', clock: 'Đồng hồ', drawing: 'Vẽ', spreadsheet: 'Bảng tính', calendar: 'Lịch', settings: 'Cài đặt', theme: 'Chủ đề', lightTheme: 'Sáng', darkTheme: 'Tối', background: 'Nền', backgroundPosition: 'Vị trí', chooseImage: 'Chọn', clearImage: 'Xóa', opacity: 'Độ mờ', language: 'Ngôn ngữ', noteTitle: 'Tiêu đề', noteContent: 'Nội dung...', taskPlaceholder: 'Thêm', save: 'Lưu', secretCode: 'Mã bí mật' },
  th: { title: 'App', search: 'ค้นหา...', empty: 'ว่างเปล่า', addNote: 'บันทึก', addTodo: 'รายการที่ต้องทำ', textMode: 'ข้อความ', todoMode: 'งาน', calculator: 'เครื่องคิดเลข', clock: 'นาฬิกา', drawing: 'วาด', spreadsheet: 'สเปรดชีต', calendar: 'ปฏิทิน', settings: 'การตั้งค่า', theme: 'ธีม', lightTheme: 'สว่าง', darkTheme: 'มืด', background: 'พื้นหลัง', backgroundPosition: 'ตำแหน่ง', chooseImage: 'เลือก', clearImage: 'ลบ', opacity: 'ความทึบ', language: 'ภาษา', noteTitle: 'ชื่อเรื่อง', noteContent: 'เนื้อหา...', taskPlaceholder: 'เพิ่ม', save: 'บันทึก', secretCode: 'รหัสลับ' },
  id: { title: 'App', search: 'Cari...', empty: 'Kosong.', addNote: 'Catatan', addTodo: 'Daftar Tugas', textMode: 'Teks', todoMode: 'Tugas', calculator: 'Kalkulator', clock: 'Jam', drawing: 'Menggambar', spreadsheet: 'Spreadsheet', calendar: 'Kalender', settings: 'Pengaturan', theme: 'Tema', lightTheme: 'Terang', darkTheme: 'Gelap', background: 'Latar', backgroundPosition: 'Posisi', chooseImage: 'Pilih', clearImage: 'Hapus', opacity: 'Opasitas', language: 'Bahasa', noteTitle: 'Judul', noteContent: 'Isi...', taskPlaceholder: 'Tambah', save: 'Simpan', secretCode: 'Kode Rahasia' },
  uk: { title: 'App', search: 'Пошук...', empty: 'Немає нотаток.', addNote: 'Нотатка', addTodo: 'Список завдань', textMode: 'Текст', todoMode: 'Завдання', calculator: 'Калькулятор', clock: 'Годинник', drawing: 'Малювання', spreadsheet: 'Таблиця', calendar: 'Календар', settings: 'Налаштування', theme: 'Тема', lightTheme: 'Світла', darkTheme: 'Темна', background: 'Фон', backgroundPosition: 'Позиція', chooseImage: 'Вибрати', clearImage: 'Видалити', opacity: 'Непрозорість', language: 'Мова', noteTitle: 'Заголовок', noteContent: 'Текст...', taskPlaceholder: 'Додати', save: 'Зберегти', secretCode: 'Секретний код' },
  fa: { title: 'برنامه', search: 'جستجو...', empty: 'یادداشتی نیست.', addNote: 'یادداشت', addTodo: 'لیست انجام کار', textMode: 'متن', todoMode: 'لیست', calculator: 'ماشین حساب', clock: 'ساعت', drawing: 'نقاشی', spreadsheet: 'صفحه گسترده', calendar: 'تقویم', settings: 'تنظیمات', theme: 'پوسته', lightTheme: 'روشن', darkTheme: 'تاریک', background: 'پس زمینه', backgroundPosition: 'موقعیت', chooseImage: 'انتخاب تصویر', clearImage: 'حذف', opacity: 'شفافیت', language: 'زبان', noteTitle: 'عنوان', noteContent: 'محتوا...', taskPlaceholder: 'افزودن کار', save: 'ذخیره', secretCode: 'کد مخفی' },
  ur: { title: 'ایپ', search: 'تلاش...', empty: 'کوئی نوٹ نہیں۔', addNote: 'نوٹ', addTodo: 'کام کی فہرست', textMode: 'متن', todoMode: 'فہرست', calculator: 'کیلکولیٹر', clock: 'گھڑی', drawing: 'ڈرائنگ', spreadsheet: 'اسپریڈشیٹ', calendar: 'کیلنڈر', settings: 'ترتیبات', theme: 'تھیم', lightTheme: 'ہلکا', darkTheme: 'تاریک', background: 'پس منظر', backgroundPosition: 'پوزیشن', chooseImage: 'تصویر منتخب کریں', clearImage: 'صاف کریں', opacity: 'شفافیت', language: 'زبان', noteTitle: 'عنوان', noteContent: 'مواد...', taskPlaceholder: 'کام شامل کریں', save: 'محفوظ کریں', secretCode: 'خفیہ کوڈ' },
  bn: { title: 'অ্যাপ', search: 'অনুসন্ধান...', empty: 'কোন নোট নেই।', addNote: 'নোট', addTodo: 'করণীয় তালিকা', textMode: 'পাঠ্য', todoMode: 'তালিকা', calculator: 'ক্যালকুলেটর', clock: 'ঘড়ি', drawing: 'অঙ্কন', spreadsheet: 'স্প্রেডশিট', calendar: 'ক্যালেন্ডার', settings: 'সেটিংস', theme: 'থিম', lightTheme: 'হালকা', darkTheme: 'গাঢ়', background: 'পটভূমি', backgroundPosition: 'অবস্থান', chooseImage: 'ছবি নির্বাচন করুন', clearImage: 'মুছে ফেলুন', opacity: 'অস্বচ্ছতা', language: 'ভাষা', noteTitle: 'শিরোনাম', noteContent: 'বিষয়বস্তু...', taskPlaceholder: 'কাজ যোগ করুন', save: 'সংরক্ষণ করুন', secretCode: 'গোপন কোড' },
  sw: { title: 'App', search: 'Tafuta...', empty: 'Hakuna noti.', addNote: 'Noti', addTodo: 'Orodha', textMode: 'Nakala', todoMode: 'Orodha', calculator: 'Kikokotoo', clock: 'Saa', drawing: 'Mchoro', spreadsheet: 'Lajedwali', calendar: 'Kalenda', settings: 'Mipangilio', theme: 'Mandhari', lightTheme: 'Nyeupe', darkTheme: 'Giza', background: 'Mandhari nyuma', backgroundPosition: 'Nafasi', chooseImage: 'Chagua Picha', clearImage: 'Futa', opacity: 'Uwazi', language: 'Lugha', noteTitle: 'Kichwa', noteContent: 'Yaliyomo...', taskPlaceholder: 'Ongeza', save: 'Hifadhi', secretCode: 'Msimbo wa siri' },
  ms: { title: 'App', search: 'Cari...', empty: 'Kosong.', addNote: 'Nota', addTodo: 'Senarai Tugas', textMode: 'Teks', todoMode: 'Tugas', calculator: 'Kalkulator', clock: 'Jam', drawing: 'Lukisan', spreadsheet: 'Hamparan', calendar: 'Kalendar', settings: 'Tetapan', theme: 'Tema', lightTheme: 'Cerah', darkTheme: 'Gelap', background: 'Latar Belakang', backgroundPosition: 'Kedudukan', chooseImage: 'Pilih Imej', clearImage: 'Padam', opacity: 'Kelegapan', language: 'Bahasa', noteTitle: 'Tajuk', noteContent: 'Kandungan...', taskPlaceholder: 'Tambah', save: 'Simpan', secretCode: 'Kod Rahsia' },
  el: { title: 'App', search: 'Αναζήτηση...', empty: 'Καμία σημείωση.', addNote: 'Σημείωση', addTodo: 'Λίστα εργασιών', textMode: 'Κείμενο', todoMode: 'Λίστα', calculator: 'Αριθμομηχανή', clock: 'Ρολόι', drawing: 'Σχέδιο', spreadsheet: 'Υπολογιστικό φύλλο', calendar: 'Ημερολόγιο', settings: 'Ρυθμίσεις', theme: 'Θέμα', lightTheme: 'Ανοιχτό', darkTheme: 'Σκούρο', background: 'Φόντο', backgroundPosition: 'Θέση', chooseImage: 'Επιλογή εικόνας', clearImage: 'Καθαρισμός', opacity: 'Αδιαφάνεια', language: 'Γλώσσα', noteTitle: 'Τίτλος', noteContent: 'Περιεχόμενο...', taskPlaceholder: 'Προσθήκη', save: 'Αποθήκευση', secretCode: 'Μυστικός κωδικός' },
  he: { title: 'App', search: 'Search...', empty: 'No notes yet. Tap + to add.', addNote: 'Text Note', addTodo: 'To-Do List', textMode: 'Text', todoMode: 'To-Do', calculator: 'Calculator', clock: 'Clock', drawing: 'Drawing', spreadsheet: 'Spreadsheet', calendar: 'Calendar', settings: 'Settings', theme: 'Theme', lightTheme: 'Light', darkTheme: 'Dark', background: 'Background', backgroundPosition: 'Position', chooseImage: 'Choose Image', clearImage: 'Clear Image', opacity: 'UI Opacity', language: 'Language', noteTitle: 'Title', noteContent: 'Content...', taskPlaceholder: 'Add Task', save: 'Save', secretCode: 'Secret Code' },
  da: { title: 'App', search: 'Search...', empty: 'No notes yet. Tap + to add.', addNote: 'Text Note', addTodo: 'To-Do List', textMode: 'Text', todoMode: 'To-Do', calculator: 'Calculator', clock: 'Clock', drawing: 'Drawing', spreadsheet: 'Spreadsheet', calendar: 'Calendar', settings: 'Settings', theme: 'Theme', lightTheme: 'Light', darkTheme: 'Dark', background: 'Background', backgroundPosition: 'Position', chooseImage: 'Choose Image', clearImage: 'Clear Image', opacity: 'UI Opacity', language: 'Language', noteTitle: 'Title', noteContent: 'Content...', taskPlaceholder: 'Add Task', save: 'Save', secretCode: 'Secret Code' },
  fi: { title: 'App', search: 'Search...', empty: 'No notes yet. Tap + to add.', addNote: 'Text Note', addTodo: 'To-Do List', textMode: 'Text', todoMode: 'To-Do', calculator: 'Calculator', clock: 'Clock', drawing: 'Drawing', spreadsheet: 'Spreadsheet', calendar: 'Calendar', settings: 'Settings', theme: 'Theme', lightTheme: 'Light', darkTheme: 'Dark', background: 'Background', backgroundPosition: 'Position', chooseImage: 'Choose Image', clearImage: 'Clear Image', opacity: 'UI Opacity', language: 'Language', noteTitle: 'Title', noteContent: 'Content...', taskPlaceholder: 'Add Task', save: 'Save', secretCode: 'Secret Code' },
  no: { title: 'App', search: 'Search...', empty: 'No notes yet. Tap + to add.', addNote: 'Text Note', addTodo: 'To-Do List', textMode: 'Text', todoMode: 'To-Do', calculator: 'Calculator', clock: 'Clock', drawing: 'Drawing', spreadsheet: 'Spreadsheet', calendar: 'Calendar', settings: 'Settings', theme: 'Theme', lightTheme: 'Light', darkTheme: 'Dark', background: 'Background', backgroundPosition: 'Position', chooseImage: 'Choose Image', clearImage: 'Clear Image', opacity: 'UI Opacity', language: 'Language', noteTitle: 'Title', noteContent: 'Content...', taskPlaceholder: 'Add Task', save: 'Save', secretCode: 'Secret Code' },
  cs: { title: 'App', search: 'Search...', empty: 'No notes yet. Tap + to add.', addNote: 'Text Note', addTodo: 'To-Do List', textMode: 'Text', todoMode: 'To-Do', calculator: 'Calculator', clock: 'Clock', drawing: 'Drawing', spreadsheet: 'Spreadsheet', calendar: 'Calendar', settings: 'Settings', theme: 'Theme', lightTheme: 'Light', darkTheme: 'Dark', background: 'Background', backgroundPosition: 'Position', chooseImage: 'Choose Image', clearImage: 'Clear Image', opacity: 'UI Opacity', language: 'Language', noteTitle: 'Title', noteContent: 'Content...', taskPlaceholder: 'Add Task', save: 'Save', secretCode: 'Secret Code' },
  hu: { title: 'App', search: 'Search...', empty: 'No notes yet. Tap + to add.', addNote: 'Text Note', addTodo: 'To-Do List', textMode: 'Text', todoMode: 'To-Do', calculator: 'Calculator', clock: 'Clock', drawing: 'Drawing', spreadsheet: 'Spreadsheet', calendar: 'Calendar', settings: 'Settings', theme: 'Theme', lightTheme: 'Light', darkTheme: 'Dark', background: 'Background', backgroundPosition: 'Position', chooseImage: 'Choose Image', clearImage: 'Clear Image', opacity: 'UI Opacity', language: 'Language', noteTitle: 'Title', noteContent: 'Content...', taskPlaceholder: 'Add Task', save: 'Save', secretCode: 'Secret Code' },
  ro: { title: 'App', search: 'Search...', empty: 'No notes yet. Tap + to add.', addNote: 'Text Note', addTodo: 'To-Do List', textMode: 'Text', todoMode: 'To-Do', calculator: 'Calculator', clock: 'Clock', drawing: 'Drawing', spreadsheet: 'Spreadsheet', calendar: 'Calendar', settings: 'Settings', theme: 'Theme', lightTheme: 'Light', darkTheme: 'Dark', background: 'Background', backgroundPosition: 'Position', chooseImage: 'Choose Image', clearImage: 'Clear Image', opacity: 'UI Opacity', language: 'Language', noteTitle: 'Title', noteContent: 'Content...', taskPlaceholder: 'Add Task', save: 'Save', secretCode: 'Secret Code' },
  sk: { title: 'App', search: 'Search...', empty: 'No notes yet. Tap + to add.', addNote: 'Text Note', addTodo: 'To-Do List', textMode: 'Text', todoMode: 'To-Do', calculator: 'Calculator', clock: 'Clock', drawing: 'Drawing', spreadsheet: 'Spreadsheet', calendar: 'Calendar', settings: 'Settings', theme: 'Theme', lightTheme: 'Light', darkTheme: 'Dark', background: 'Background', backgroundPosition: 'Position', chooseImage: 'Choose Image', clearImage: 'Clear Image', opacity: 'UI Opacity', language: 'Language', noteTitle: 'Title', noteContent: 'Content...', taskPlaceholder: 'Add Task', save: 'Save', secretCode: 'Secret Code' }
};

export const getT = (locale: Locale): Translation => translations[locale] || translations.en;
